[project]
name = "mochila-ic236ep"
version = "0.1.0"
description = ""
authors = [
    {name = "gladsonandrade",email = "112895566+gladsonandrade@users.noreply.github.com"}
]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "matplotlib (>=3.10.9,<4.0.0)",
    "numpy (>=2.4.6,<3.0.0)"
]

[tool.poetry]
packages = [{include = "mochila_ic236ep", from = "src"}]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
